name: 13
timestamp: 1473426734
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1471875073
positions:
  overlay-top: 'Overlay Top'
  overlay-a: 'Overlay A'
  overlay-b: 'Overlay B'
  overlay-c: 'Overlay C'
  header-a: 'Header A'
  header-b: 'Header B'
  header-c: 'Header C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
  footer-a: 'Footer A'
  footer-b: 'Footer B'
  footer-c: 'Footer C'
  footer-d: 'Footer D'
