preset: preset3
base:
  background: '#f9f9f9'
accent:
  color-1: '#0d602e'
  color-2: '#d76100'
  color-3: '#ac0062'
header:
  background: '#0d602e'
above:
  background: '#f9f9f9'
feature:
  background: '#0d602e'
expanded:
  background: '#f9f9f9'
extension:
  background: '#0d602e'
copyright:
  background: 'rgba(0, 0, 0, 1)'
offcanvas:
  background: '#008c00'
  toggle-color: '#0d602e'
main:
  background: '#f9f9f9'
overlay:
  background: '#0d602e'
