name: 9
timestamp: 1476730812
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1471875073
positions:
  overlay-top: 'Overlay Top'
  overlay-a: 'Overlay A'
  overlay-b: 'Overlay B'
  overlay-c: 'Overlay C'
  above-a: 'Above A'
  above-b: 'Above B'
  above-c: 'Above C'
  showcase-a: 'Showcase A'
  showcase-b: 'Showcase B'
  showcase-c: 'Showcase C'
  utility-a: 'Utility A'
  utility-b: 'Utility B'
  utility-c: 'Utility C'
  feature-a: 'Feature A'
  feature-b: 'Feature B'
  feature-c: 'Feature C'
  sidebar: Sidebar
  mainbar-a: 'Mainbar A'
  mainbar-b: 'Mainbar B'
  mainbar-c: 'Mainbar C'
  aside: Aside
  expanded-a: 'Expanded A'
  expanded-b: 'Expanded B'
  expanded-c: 'Expanded C'
  extension-a: 'Extension A'
  extension-b: 'Extension B'
  extension-c: 'Extension C'
  bottom-a: 'Bottom A'
  bottom-b: 'Bottom B'
  bottom-c: 'Bottom C'
sections:
  overlay: Overlay
  top: Top
  navigation: Navigation
  above: Above
  showcase: Showcase
  utility: Utility
  feature: Feature
  sidebar: Sidebar
  mainbar: Mainbar
  expanded: Expanded
  extension: Extension
  bottom: Bottom
  copyright: Copyright
  header: Header
  aside: Aside
  footer: Footer
  offcanvas: Offcanvas
particles:
  position:
    position-position-1846: 'Overlay Top'
    position-position-5278: 'Overlay A'
    position-position-8786: 'Overlay B'
    position-position-9848: 'Overlay C'
    position-above-a: 'Above A'
    position-above-b: 'Above B'
    position-above-c: 'Above C'
    position-showcase-a: 'Showcase A'
    position-showcase-b: 'Showcase B'
    position-showcase-c: 'Showcase C'
    position-utility-a: 'Utility A'
    position-utility-b: 'Utility B'
    position-utility-c: 'Utility C'
    position-feature-a: 'Feature A'
    position-feature-b: 'Feature B'
    position-feature-c: 'Feature C'
    position-sidebar: Sidebar
    position-mainbar-a: 'Mainbar A'
    position-mainbar-b: 'Mainbar B'
    position-mainbar-c: 'Mainbar C'
    position-aside: Aside
    position-expanded-a: 'Expanded A'
    position-expanded-b: 'Expanded B'
    position-expanded-c: 'Expanded C'
    position-extension-a: 'Extension A'
    position-extension-b: 'Extension B'
    position-extension-c: 'Extension C'
    position-bottom-a: 'Bottom A'
    position-bottom-b: 'Bottom B'
    position-bottom-c: 'Bottom C'
  module:
    position-module-3889: 'Header Logo/Social'
    position-module-9397: Breadcrumb
    position-module-1962: Partners
  menu:
    menu-3995: Menu
  messages:
    system-messages-1193: 'System Messages'
  content:
    system-content-5020: 'Page Content'
  branding:
    branding-3018: Branding
  copyright:
    copyright-5323: Copyright
  totop:
    totop-8334: 'To Top'
  mobile-menu:
    mobile-menu-8402: 'Mobile Menu'
inherit: {  }
