version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1471875073
layout:
  /overlay/:
    -
      - position-position-1846
    -
      - 'position-position-5278 33.3'
      - 'position-position-8786 33.3'
      - 'position-position-9848 33.3'
  /top/: {  }
  /navigation/: {  }
  /header/:
    -
      - position-module-3889
    -
      - menu-3995
  /above/:
    -
      - position-module-9397
    -
      - 'position-above-a 33.3'
      - 'position-above-b 33.3'
      - 'position-above-c 33.3'
  /showcase/:
    -
      - 'position-showcase-a 33.3'
      - 'position-showcase-b 33.3'
      - 'position-showcase-c 33.3'
  /utility/:
    -
      - 'position-utility-a 33.3'
      - 'position-utility-b 33.3'
      - 'position-utility-c 33.3'
  /feature/:
    -
      - 'position-feature-a 33.3'
      - 'position-feature-b 33.3'
      - 'position-feature-c 33.3'
  /container-main/:
    -
      -
        'sidebar 20':
          -
            - position-sidebar
      -
        'mainbar 60':
          -
            - 'position-mainbar-a 33.3'
            - 'position-mainbar-b 33.3'
            - 'position-mainbar-c 33.3'
          -
            - system-messages-1193
          -
            - system-content-5020
      -
        'aside 20':
          -
            - position-aside
  /expanded/:
    -
      - 'position-expanded-a 33.3'
      - 'position-expanded-b 33.3'
      - 'position-expanded-c 33.3'
  /extension/:
    -
      - 'position-extension-a 33.3'
      - 'position-extension-b 33.3'
      - 'position-extension-c 33.3'
  /bottom/:
    -
      - 'position-bottom-a 33.3'
      - 'position-bottom-b 33.3'
      - 'position-bottom-c 33.3'
  /footer/:
    -
      - position-module-1962
  /copyright/:
    -
      - 'branding-3018 33.3'
      - 'copyright-5323 33.3'
      - 'totop-8334 33.3'
  /offcanvas/:
    -
      - mobile-menu-8402
structure:
  overlay:
    type: section
    attributes:
      boxed: ''
  top:
    type: section
    attributes:
      boxed: '2'
      class: ''
  navigation:
    type: section
    attributes:
      boxed: '2'
      class: ''
  header:
    attributes:
      boxed: '2'
      class: ''
  above:
    type: section
    attributes:
      boxed: '2'
      class: ''
  showcase:
    type: section
    attributes:
      boxed: '1'
      class: ''
  utility:
    type: section
    attributes:
      boxed: '1'
      class: ''
  feature:
    type: section
    attributes:
      boxed: '1'
      class: ''
  sidebar:
    type: section
    attributes:
      class: ''
    block:
      class: equal-height
  mainbar:
    type: section
    attributes:
      class: ''
    block:
      class: equal-height
  aside:
    attributes:
      class: ''
    block:
      class: equal-height
  container-main:
    attributes:
      boxed: '1'
      class: ''
      extra: {  }
  expanded:
    type: section
    attributes:
      boxed: '1'
      class: ''
  extension:
    type: section
    attributes:
      boxed: '1'
      class: ''
  bottom:
    type: section
    attributes:
      boxed: '1'
      class: ''
  footer:
    attributes:
      boxed: '1'
      class: ''
  copyright:
    type: section
    attributes:
      boxed: '0'
      class: ''
  offcanvas:
    attributes:
      boxed: ''
content:
  position-position-1846:
    title: 'Overlay Top'
    attributes:
      key: overlay-top
    block:
      class: fp-overlay-top
  position-position-5278:
    title: 'Overlay A'
    attributes:
      key: overlay-a
  position-position-8786:
    title: 'Overlay B'
    attributes:
      key: overlay-b
  position-position-9848:
    title: 'Overlay C'
    attributes:
      key: overlay-c
  position-module-3889:
    title: 'Header Logo/Social'
    attributes:
      module_id: '141'
    block:
      class: g-header-custom
  menu-3995:
    block:
      class: g-header-menu
  position-module-9397:
    title: Breadcrumb
    attributes:
      module_id: '88'
      key: breadcrumb
    block:
      class: custom-breadcrumb
  position-above-a:
    title: 'Above A'
    attributes:
      key: above-a
  position-above-b:
    title: 'Above B'
    attributes:
      key: above-b
  position-above-c:
    title: 'Above C'
    attributes:
      key: above-c
  position-showcase-a:
    title: 'Showcase A'
    attributes:
      key: showcase-a
  position-showcase-b:
    title: 'Showcase B'
    attributes:
      key: showcase-b
  position-showcase-c:
    title: 'Showcase C'
    attributes:
      key: showcase-c
  position-utility-a:
    title: 'Utility A'
    attributes:
      key: utility-a
  position-utility-b:
    title: 'Utility B'
    attributes:
      key: utility-b
  position-utility-c:
    title: 'Utility C'
    attributes:
      key: utility-c
  position-feature-a:
    title: 'Feature A'
    attributes:
      key: feature-a
  position-feature-b:
    title: 'Feature B'
    attributes:
      key: feature-b
  position-feature-c:
    title: 'Feature C'
    attributes:
      key: feature-c
  position-sidebar:
    attributes:
      key: sidebar
  position-mainbar-a:
    title: 'Mainbar A'
    attributes:
      key: mainbar-a
  position-mainbar-b:
    title: 'Mainbar B'
    attributes:
      key: mainbar-b
  position-mainbar-c:
    title: 'Mainbar C'
    attributes:
      key: mainbar-c
  position-aside:
    attributes:
      key: aside
  position-expanded-a:
    title: 'Expanded A'
    attributes:
      key: expanded-a
  position-expanded-b:
    title: 'Expanded B'
    attributes:
      key: expanded-b
  position-expanded-c:
    title: 'Expanded C'
    attributes:
      key: expanded-c
  position-extension-a:
    title: 'Extension A'
    attributes:
      key: extension-a
  position-extension-b:
    title: 'Extension B'
    attributes:
      key: extension-b
  position-extension-c:
    title: 'Extension C'
    attributes:
      key: extension-c
  position-bottom-a:
    title: 'Bottom A'
    attributes:
      key: bottom-a
  position-bottom-b:
    title: 'Bottom B'
    attributes:
      key: bottom-b
  position-bottom-c:
    title: 'Bottom C'
    attributes:
      key: bottom-c
  position-module-1962:
    title: Partners
    attributes:
      module_id: '138'
      key: partners
    block:
      class: g-footer-banners
  branding-3018:
    attributes:
      content: ''
      css:
        class: ''
  copyright-5323:
    attributes:
      date:
        start: '2016'
      owner: 'FC Mirefleurs'
  totop-8334:
    title: 'To Top'
    attributes:
      icon: ''
      content: 'To Top'
  mobile-menu-8402:
    title: 'Mobile Menu'
