ordering:
  accueil: ''
  equipes:
    seniors-1:
      effectif-staff: ''
      calendrier-resultats: ''
      classement: ''
      statistiques: ''
    seniors-2:
      effectif-staff: ''
      calendrier-resultats: ''
      classement: ''
      statistiques: ''
  actualites: ''
  calendrier: ''
  club:
    presentation: ''
    organigramme: ''
    partenaires: ''
  medias:
    photos: ''
    videos: ''
  __module-RLbez: ''
items:
  accueil:
    id: 103
    dropdown_hide: ''
    width: auto
    icon: 'fa fa-home'
  club:
    id: 104
    dropdown_hide: ''
    width: auto
  club/partenaires:
    id: 108
    dropdown_hide: ''
    width: auto
  actualites:
    id: 105
    dropdown_hide: ''
    width: auto
  styles/__particle-lklZ7:
    type: particle
    particle: custom
    title: 'Custom HTML'
    options:
      particle:
        enabled: '1'
        html: "<div class=\"g-grid g-preset-thumbnails center\">\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset1\">\n                <img src=\"images/rocketlauncher/styles/preset1.jpg\" alt=\"Preset 1\">\n                <br>\n                <span>Preset 1</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset2\">\n                <img src=\"images/rocketlauncher/styles/preset2.jpg\" alt=\"Preset 2\">\n                <br>\n                <span>Preset 2</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset3\">\n                <img src=\"images/rocketlauncher/styles/preset3.jpg\" alt=\"Preset 3\">\n                <br>\n                <span>Preset 3</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset4\">\n                <img src=\"images/rocketlauncher/styles/preset4.jpg\" alt=\"Preset 4\">\n                <br>\n                <span>Preset 4</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset5\">\n                <img src=\"images/rocketlauncher/styles/preset5.jpg\" alt=\"Preset 5\">\n                <br>\n                <span>Preset 5</span>\n            </a>\n        </div>\n    </div>\n    <div class=\"g-block\">\n        <div class=\"g-content\">\n            <a href=\"?presets=preset6\">\n                <img src=\"images/rocketlauncher/styles/preset6.jpg\" alt=\"Preset 6\">\n                <br>\n                <span>Preset 6</span>\n            </a>\n        </div>\n    </div>    \n</div>"
      block:
        extra: {  }
    enabled: true
    anchor_class: ''
  __module-RLbez:
    type: particle
    particle: module
    title: Recherche
    options:
      particle:
        enabled: '1'
        module_id: '142'
        chrome: ''
      block:
        class: g-menu-search
        extra: {  }
    enabled: true
    anchor_class: ''
